import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
import ReactQueryWrapper from "./components/reactQueryWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{ display: "flex", justifyContent: "center" }}>
          {/* Your header content here */}
          <h1>Medicare App</h1>
        </header>
        <main className={styles.main}>
          <ReactQueryWrapper>
            {children}
          </ReactQueryWrapper>
        </main>
        <footer>
          {/* Your footer content here */}
          <p style={{ display: "flex", justifyContent: "center" }}>
            Copyright &copy; 2024
          </p>
        </footer>
      </body>
    </html>
  );
}
